# action.yml
name: 'Nosey Parker'
description: 'Scan repository for secrets'
inputs:
  github-username:  # id of input
    description: 'github username to scan'
    required: true

outputs:
  time: # id of output
    description: 'The initial runtime.'
  np_status_code:
    description: 'Status code of the noseyparker scan command.'
  np_status:
    description: 'Descriptive status of noseyparker scan command.'
  np_summary:
    description: 'Output of noseyparker summary command.'
  np_report:
    description: 'Output of noseparker report command.'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}