# action.yml
name: 'Nosey Parker'
description: 'Scan repository for secrets'
inputs:
  upload-reports:
    description: 'upload reports'
    required: false
    default: 'true'
  report-format-human:
    description: 'upload human formatted report'
    required: false
    default: 'true'
  report-format-json:
    description: 'upload json formatted report'
    required: false
    default: 'false'
  report-format-jsonl:
    description: 'upload jsonl formatted report'
    required: false
    default: 'false'
  report-format-sarif:
    description: 'upload sarif formatted report'
    required: false
    default: 'false'
  scan-directory:
    description: 'relative directory of the repo to scan from $GITHUB_WORKSPACE'
    required: false
    default: 'main'
  fail-on-finding:
    description: 'set to true to interrupt the pipeline if there are any findings.'
    required: true
    default: 'true'

outputs:
  time: # id of output
    description: 'The initial runtime.'
  np_status_code:
    description: 'Status code of the noseyparker scan command.'
  np_status:
    description: 'Descriptive status of noseyparker scan command.'
  # np_summary:
  #   description: 'Output of noseyparker summary command.'
  # np_report:
  #   description: 'Output of noseparker report command.'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.upload-reports }}
    - ${{ inputs.report-format-human }}
    - ${{ inputs.report-format-json }}
    - ${{ inputs.report-format-jsonl }}
    - ${{ inputs.report-format-sarif }}
    - ${{ inputs.scan-directory }}
    - ${{ inputs.fail-on-finding }}